### ISSUE TITLE
add support to gpu devices in cgroups

### ISSUE THREAD

**Issue by nniclausse** [oar-team/oar#107]
Would it be possible to add support for gpu in cgroups in OAR ?

It seems that cgroup can allow or deny access to devices (so /dev/nvidiaXX)

http://slurm.schedmd.com/slurm_ug_2011/SLURM_UserGroup2011_cgroups.pdf

If we add a gpudevices column in the resource table, we could associate 0, one or several gpu per core:
cpuset :     "0" "1" "2"  "3"
gpudevice  "0" "1" NULL NULL

for the nvidia case, oar could set the CUDA_VISIBLE_DEVICES variable in the user shell based on the gpudevices allocated to the job

say if user has reserved one core (cpuset=1) it will have, so
CUDA_VISIBLE_DEVICES=1

if he reesrve core 0 and 1, then  CUDA_VISIBLE_DEVICES=0,1

a user can book gpu using something like oarsub -l {gpudevices<>NULL}/nodes=1/core=XX

we could also handle several gpus per core (using gpudevice= "0+1"  or "0,1"), but the syntax to reserve a specific amount of gpus is more tricky in this case

**Comment by capitn** [comment]
First there are 2 points to keep in mind:

  - OAR handles resources in an implicit hierarchical manner.
    If you reserve a host then you reserve the cpu (sockets) and the cores of
    this host.
    So if we declare a "gpudevice" property it is not fitting well in this
    hierarchy. We must do something like "if you reserve the core n°1 then you
    reserve also the gpudevice n°1" and so on.
    It is not very flexible but it is working.

  - I have no feedback about the cgroup "devices" feature. So I don't know if
    the NVIDIA driver is working correctly if you are not able to access all the
    server GPUs from a process.
    So several tests must be performed (I think it is working now but in the
    past there were some issues).

Currently when I configure a cluster with some GPU nodes I declare 3 resource
properties:

  - gpu: with the values "YES" or "NO".
  - gpudevice: the ID of the GPU inside a node.
  - gpunum: the global ID of the GPU in the cluster (like the "core" property).

Then I decide which GPU I associate with which cores. To do this I take a look
at the "nvidia-smi" and "lstopo" command to find where the GPU are plugged into
the node (which PCI slot on which socket).
Once it is decided I update the OAR resource table, for example (a 4 core node
with 2 GPUs):

    oarnodesetting --sql "host='gpu02' and cpuset=0" -p gpudevice=0 -p gpunum=13
    oarnodesetting --sql "host='gpu02' and cpuset=1" -p gpudevice=0 -p gpunum=13
    oarnodesetting --sql "host='gpu02' and cpuset=2" -p gpudevice=1 -p gpunum=14
    oarnodesetting --sql "host='gpu02' and cpuset=3" -p gpudevice=1 -p gpunum=14

So the users can do:

    # Reserve 1 GPU on 1 node and, implicitly, 2 cores
    oarsub -I -l "{gpu='YES'}/host=1/gpunum=1"
        # To get which GPU they must use on which host
        oarprint host -P host,gpudevice

    # We can share a GPU with another job
    oarsub -I -l "{gpu='YES'}/host=1/core=1"

But there is no restriction, the user can use all the GPUs of the node if he
wants.


To add the restriction we must use the cgroup "devices" in the
/etc/oar/job_resource_manager_cgroups.pl script.
I think it is doable because, in this script, we have:

  - the possibility to mount or not the cgroup "devices".
  - all the resources assigned to the job are available (so the "gpudevice" property for each
    node).
  - we can also add the right "CUDA_VISIBLE_DEVICES" environment variable in
    the file that is sourced by the job processes on each job node.
    So it could be automatic for the users.

I think this could be implemented like the cgroup "memory" which can be turned on
or off with:

    my $ENABLE_MEMCG = "YES";

-->  my $ENABLE_DEVICECG = "YES";

Could someone test on a GPU node if the cgroup "devices" is working correcly
with the NVIDIA driver and a cuda job?
(mount the cgroup, enable or disable some GPU devices, add manually the job
processes inside and launch a cuda process)

If these tests are OK then I can work on the script to implement this
automatically.

**Comment by nniclausse** [comment]
I did a first test and it seems to work:
I have a job on a node with 7 gpu (devices  195:[0-6] )
i did as root:
echo 'c 195:6 rwm' > /sys/fs/cgroup/devices/oar/nniclaus_243468/devices.deny
echo 'c 195:5 rwm' > /sys/fs/cgroup/devices/oar/nniclaus_243468/devices.deny

and nvidia-smi show me only 5 GPU (devicesquery also), no need to set CUDA_VISIBLE_DEVICES

(i'm using cuda 7.5)

**Comment by npf** [comment]
Hello,

So looks likes like this would only involve modifying "configuration" files (/etc/oar/ -> job_resource_manager) and the resources (database).

oarsh_shell would not need modified for instance. 

If so, that would not necessarily need to be part of OAR sources, and delay 2.5.7 ?

**Comment by nniclausse** [comment]
the job_resource_manager_cgroups.pl is part of the OAR sources, so it would be nice if this default script is gpu aware, but it can be postpone after 2.5.7

**Comment by npf** [comment]
Yes of course. The point is 2.5.7 if for tonight :-)

**Comment by nniclausse** [comment]
I did a quick and dirty implementation, and it works as expected !
 (i can submit a PR if you wish)

      if ($ENABLE_DEVICECG eq "YES" ){
            my @devices_deny;
            opendir my($dh), "/dev"  or continue;
            my @files = grep { /nvidia/ } readdir $dh;
            foreach (@files) {
                if ($_ =~ /nvidia(\d+)/ ) {
                    push  @devices_deny, $1;
                }
            }
            closedir $dh;
            if ($#devices_deny > -1) {
                # now remove from denied devices our reserved devices
                foreach my $r (@{$Cpuset->{'resources'}}){
                    if ($r->{'gpudevice'} ne '' ){
                        @devices_deny = grep { $_ !=  $r->{'gpudevice'} } @devices_deny;
                    }
                }
                my $devices_cgroup = $Cgroup_directory_collection_links."/devices".$Cpuset_path_job."/devices.deny";
                foreach my $dev (@devices_deny){
                    if (system("oardodo /bin/echo 'c 195:$dev rwm' > $devices_cgroup")) {
                        exit_myself(5,"Failed to set the devices.deny to c 195:$dev rwm");
                    }
                }
            }
        }

**Comment by capitn** [comment]
I will take a look at this patch and try to commit it in the 2.5 branch.

**Comment by nniclausse** [comment]
I installed your version and it seems to be fine, thanks !

**Comment by npf** [comment]
> There is one thing I don't understand, why do we need oardodo (be root) in:
> system("oardodo /bin/echo 'c 195:$dev rwm' > $devices_cgroup")

Seems like even if the "special" file can be opened by its owner (which is oar, not root, in our case), only root can write to it... Not sure if it qualify for a bug.

**Comment by npf** [comment]
I add ed some doc in the contrib section of the wiki:
https://oar.imag.fr/wiki:managing_gpu_resources

**Comment by npf** [comment]
For ref: 
<code bash>
$ cd /dev/oar_cgroups_links/devices/oar/user_1/
$ cat devices.list 
a *:* rwm
$ ls -l /dev/nvidia0
crw-rw-rw- 1 root root 195, 0 avril 14 19:06 /dev/nvidia0
docker@node1 /dev/oar_cgroups_links/devices/oar/docker_2
$ echo 'c 195:0 rwm' > devices.deny 
$ cat devices.list 
a *:* rwm
</code>
The denied device does not show up in the ''devices.list'' file (Linux3.16.0-4-amd64, Debian 3.16.7-ckt20-1+deb8u3)

**Comment by npf** [comment]
@nniclausse : what about the CUDA_VISIBLE_DEVICES environment variable ? is it useless ?

**Comment by nniclausse** [comment]
It's useless with the devices cgroup

**Comment by npf** [comment]
As of today many question still remain !:
  * how to list allowed / denied devices ? device.list does not seem to work (on Debian at least)
  * why must be `echo 'c 195:0 rwm' be run as root, while `> devices.deny` run as oar is ok.
... However it seems to work ok ⇒ not reopening
