### ISSUE TITLE
Besteffort jobs vs RESERVATION_WAITING_RESOURCES_TIMEOUT

### ISSUE THREAD

**Issue by SimonDelamare** [oar-team/oar#109]
Hello,

In Grid'5000, we have issue with reservation jobs which may get far less resources than expected if best-effort jobs are present when they start.

In some cases, our best-effort jobs need quite long time to be cleaned (in case of besteffort + deploy jobs, they need to be rebooted or even redeployed) and it causes RESERVATION_WAITING_RESOURCES_TIMEOUT to expire.

However, for general usage, we do not want to increase RESERVATION_WAITING_RESOURCES_TIMEOUT too much.

Would it be possible for OAR to improve that situation ? i.e. by killing best-effort jobs in advance when a reservation job is scheduled ?

For more info, see : https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=6335

Thanks !
Simon

**Comment by capitn** [comment]
Maybe we can do something like that but if a besteffort job is running and then a reservation is submitted to start right now the problem will still be there (if RESERVATION_WAITING_RESOURCES_TIMEOUT is not big enough).

BTW, in *oar_meta_sched* we could change
```perl
sub check_jobs_to_kill(){           
    oar_debug("[MetaSched] Begin precessing of besteffort jobs to kill\n");
    my %nodes_for_jobs_to_launch = OAR::IO::get_gantt_resources_for_jobs_to_launch($base,$current_time_sec);
```
into
```perl
sub check_jobs_to_kill(){           
    oar_debug("[MetaSched] Begin precessing of besteffort jobs to kill\n");
    my %nodes_for_jobs_to_launch = OAR::IO::get_gantt_resources_for_jobs_to_launch($base,$current_time_sec + $BESTEFFORT_KILL_DURATION);
```
and put BESTEFFORT_KILL_DURATION in oar.conf.
This will kill besteffort jobs if there is a job scheduled to start in $BESTEFFORT_KILL_DURATION on the same resources.

In this case we need also to change the default besteffort job duration in the schedulers; ex. in *oar_sched_gantt_with_timesharing_and_fairsharing_and_quotas*:
```perl
# Constant duration time of a besteffort job
my $besteffort_duration = 5*60;
```
to
```perl
my $besteffort_duration = $BESTEFFORT_KILL_DURATION;
```

**Comment by capitn** [comment]
I think we can dynamically change the RESERVATION_WAITING_RESOURCES_TIMEOUT for reservation jobs that were submitted less than BESTEFFORT_KILL_DURATION. So we handle the case where the besteffort jobs didn't have enough time to finish correctly.

--> RESERVATION_WAITING_RESOURCES_TIMEOUT += BESTEFFORT_KILL_DURATION

**Comment by SimonDelamare** [comment]
Both solutions seem fine, thanks.

**Comment by capitn** [comment]
Another point; If we consider "standard" jobs then we use SCHEDULER_JOB_SECURITY_TIME to let the time to the nodes to become available between the jobs.
So I think we can use SCHEDULER_JOB_SECURITY_TIME instead of creating BESTEFFORT_KILL_DURATION.
In this case we will kill besteffort jobs SCHEDULER_JOB_SECURITY_TIME before the beginning of the reservations.

Is this change will resolve your issue in g5k?
What is your current value of SCHEDULER_JOB_SECURITY_TIME?

**Comment by npf** [comment]
It is currently set to 120s, which is not enough for a node to be redeploy I fear (at least not in all cases).

If I understand what you mean correctly (standard jobs = batch jobs = not an adv. reservation), I would suggest to keep the possibility to give a larger time for killing best effort before the start of the adv. reservation anyway, but for rationalizing as you suggest,  maybe use `t+max(SCHEDULER_JOB_SECURITY_TIME, BESTEFFORT_KILL_DURATION)`, because it would indeed make sense to have at least t+SCHEDULER_JOB_SECURITY_TIME...

**Comment by capitn** [comment]
Culd you test this commit and put in your oar.conf `SCHEDULER_BESTEFFORT_KILL_DURATION_BEFORE_RESERVATION` with the number of seconds you want to kill in advance the besteffort jobs.

**Comment by npf** [comment]
Some additional notes for the potential early adopters of the patch:

1. This does not solve the case of advance reservations that would be created just "now" : those jobs would be accepted, not giving time to kill the besteffort job(s) beforehand. Hence the problem of not coming back in time resources would occur. A solution to that would be to actually take into account the besteffort jobs with an end time of `t = now +  max(SCHEDULER_JOB_SECURITY_TIME, BESTEFFORT_KILL_DURATION)` in the scheduling, while for now, we just dont consider besteffort jobs in the scheduling. A workaround would be to warn users thanks to an admission rule.
2. Regarding the besteffort+checkpoint: if a user gives a checkpoint in the besteffort job, this will delay the end of the besteffort job, hence causing problem to a following advance reservation as well (resources not back in time). As a workaround, the maximum allowed (by admission rule) checkpoint time could be taken into consideration ("included")  in the BESTEFFORT_KILL_DURATION. Fixing the issue would require the scheduler to look to next advance reservation with taking into account the possible checkpoint requested in the besteffort job. This implies a noticable change in the scheduler code, because the lookup for next advance reservation is to be made a function of every besteffort job (currently we only consider resources used by any besteffort job as a whole, with a same time for the wanted avalability). Also, same a 1., the scheduling should actually take into consideration besteffort job, with an end time of `t = now +  max(SCHEDULER_JOB_SECURITY_TIME, BESTEFFORT_KILL_DURATION) + checkpoint time` instead of ignoring them.

Those changes are quite noticable modifications of the scheduler, which are also most likely to come in OAR 2.6, not before (2.6. tries to make the perl scheduler development more sustainable).

**Comment by bpichot** [comment]
I tested with oardocker the commit 53ff3b5, cherry-picked on top of version 2.5.7, and it works as expected: besteffort jobs are killed (or receive a checkpoint signal) max(BESTEFFORT_KILL_DURATION, JOB_SECURITY_TIME) before the reservations, unless the reservation is submitted less than this duration in advance in which case the kill (or checkpoint signal) is performed as soon as possible, that is to say, potentially too late.

On Grid'5000 we will probably apply this patch, in addition to an admission rule to warn users who make reservations not far enough in the future that they might lose some nodes.

**Comment by npf** [comment]
@bpichot: close when you think it is ok.

**Comment by bpichot** [comment]
Patch applied on Grid'5000 (in addition to an admission rule to warn users who make reservations not far enough in the future that they might lose nodes, and another rule to limit checkpoints on besteffort jobs) and it works, thanks a lot!

**Comment by npf** [comment]
fixed in RC
