### ISSUE TITLE
"oarsub -C" reports an error when trying to connect to a noop job

### ISSUE THREAD

**Issue by bpichot** [oar-team/oar#116]
Tested with oardocker:

docker@frontend ~ 
$ oarsub -t noop -r "2016-06-07 18:47:00" -l nodes=1
[ADMISSION RULE] Set default walltime to 7200. 
[ADMISSION RULE] Modify resource description with type constraints
OAR_JOB_ID=2
Reservation mode : waiting validation...
Reservation valid --> OK

docker@frontend ~
$ oarsub -C 2
Connect to OAR job 2 via the node node2
Warning: Permanently added '[node2]:6667,[172.17.0.39]:6667' (RSA) to the list of known hosts.
oarsh: Cannot find cpuset file : /dev/cpuset//oar/docker_2/tasks
Connection to node2 closed.
[ERROR] An unknown error occured : 15616
Disconnected from OAR job 2

**Comment by bpichot** [comment]
Besides, a noop passive job is accepted by oarsub without any warning, so the user might not know that the command is not executed anywhere: 

docker@frontend ~
$ oarsub -t noop "sleep 10d"
[ADMISSION RULE] Set default walltime to 7200.
[ADMISSION RULE] Modify resource description with type constraints
OAR_JOB_ID=9

**Comment by npf** [comment]
Regarding the 2nd point:
Noop jobs can only be passive or advance reservation: interactive jobs could not be allowed since they will hang because there is not execution.
-> So it is just normal to allow passive jobs, and indeed the command is not executed. This seems acceptable for me (that does not cause an error).
