### ISSUE TITLE
oar-users and oar-devel mailing list archive/server is down

### ISSUE THREAD

**Issue by basil-fawlty** [oar-team/oar#153]
Hi,
I could not connect to the mailing list and got no respond from the mailing list owner, maybe someone here knows about it.
Thank you!

**Comment by npf** [comment]
Thanks for the notice. Unfortunately it is out of our control. The
hosting forge reports:

Since Wed May 30, 16:30 CEST, mail services for the INRIA Forge are back
to normal. But we had to disable the mailman mailing lists web
interface, due to continuous spam attacks. We're working on finding a
solution.

(https://lists.gforge.inria.fr/)

You might however be able to subscribe by sending a mail to the mailman
robot:

mailto:oar-users-request@lists.gforge.inria.fr?subject=subscribe

Regards
