### ISSUE TITLE
Tag OAR Resources

### ISSUE THREAD

**Issue by msimonin** [oar-team/oar#196]
This question emerged from a discussion here: https://gitlab.inria.fr/discovery/enoslib/-/issues/139
I'm trying here to restrict to the OAR part.

Let's assume I'm reserving two groups of machines with different
characteristics in a single job (this is a strong requirement here):

```bash
{cluster=cluster1}/nodes=1 + {gpu_model=XXX}/nodes=1

```
In return OAR give me back a flat list of resources(servers): [server1, server2].

- Is there a way to know which server correspond to which group in the general case ?

- Extension: it would be nice to allow user to tag their resources.

```bash
{cluster=cluster1}/nodes=1,tags=tag11, tag12 + {gpu_model=XXX}/nodes=1,tags=tag21
```
And retrieving the mapping in various ways (oarstat, API or even in environment variables within the job).

How does that sound ?

**Comment by npf** [comment]
Hi @msimonin ,

Unfortunately, this would imply a deep rewrite of the whole scheduling mechanism, since currently resource groups are merged very early in the process of scheduling, losing the link between the expressed wanted resource groups and the resulting obtained resources.

The OAR database, in particular, does not maintain such information, and it is not doable to just add it, unfortunately.

Sorry about that. My suggestion is to work the other way around: use the OAR API or `oarprint` to display resources in detail, so that it becomes possible to identify what is what, even in case possible resources for each group overlap...
