### ISSUE TITLE
Scheduler_priority : different behavior between -l and OR

### ISSUE THREAD

**Issue by grafitos** [oar-team/oar#203]
Hi,

I have two ressources with 

Ressource 1 = (memthread=4000, **scheduler_priority=1**)
Ressource 2 = (memthread=5000, **scheduler_priority=0**)

**When executing :**

oarsub -I -l "{memthread=4000 or memthread=5000}"/nodes=1

The reserved ressource is 2 (according to the scheduler_priority).

**And when executing :**

oarsub -I -l {memthread=4000}/nodes=1 -l {memthread=5000}/nodes=1

the reserved ressource is 1 (it seems to ignore scheduler_priority).

Is it an expected behavior ?

I know we can have multiple reservations with the +(and) operator like: oarsub -I -l {memthread=4000}/nodes=1+{memthread=5000}/nodes=1. I would expect a "or" operator to select a ressource from a set of ressources, that is aware of scheduler_priority field.

Thanks

**Comment by npf** [comment]
Yes, this is the expected behavior.

- Using multiple `-l` defines moldable job resources definitions: the scheduler will place the job accordingly to the moldable job description that fits and finishes the earliest or if end-time is that same by moldable job id. `scheduler priority` impacts the choice of resources within a moldable job. As such it does not impact the choice between several moldable jobs.
- Using a `or` with a single moldable job (only one `-l`), OAR sorts resources accordingly to their scheduler priority.
